version: '3.9'

services:
  acme:
    container_name: 'acmeapi'
    image: 'acmeapi'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      #- "5001:5001" # Uncomment if there's an SSL cert for the domain/host.
    depends_on:
      - "acme.database"
    networks:
      - acme.network

  acme.database:
    container_name: 'postgres'
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - acme.network

networks:
  acme.network:
    driver: bridge
